In [2]:
# create 4x4 arrays with all true values
import numpy as np
np.full((4,4),True,dtype=bool)


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [3]:
# create 4x4 arrays with all false values
np.full((4,4),False,dtype=bool)


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [9]:
# create 4x4 arrays whose diagonal elements are True and Non-diagonal elements are False
np.identity(4,dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [26]:
# create 4x4 arrays whose diagonal elements are False and Non-diagonal elements are True
~np.identity(4,dtype=bool)

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [18]:

a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
# multiply
np.multiply(a,10)

array([[10, 20, 30],
       [40, 50, 60]])

In [20]:
# divide
np.divide(a,2)

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [21]:
# floor_divide
np.floor_divide(a,2)

array([[0, 1, 1],
       [2, 2, 3]], dtype=int32)

In [22]:
# power
np.power(a,2)

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [23]:
# mod
np.mod(a,2)

array([[1, 0, 1],
       [0, 1, 0]], dtype=int32)